apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
commonLabels:
  environment: dev
bases:
  - ../../base
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: "6.6.0"
patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "#00FF00"
      - op: add
        path: /spec/template/metadata/labels/env
        value: dev
