---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  type: ClusterIP
  selector:
    app: rollout-bluegreen
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  type: ClusterIP
  selector:
    app: rollout-bluegreen
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
    name: http
