apiVersion: v1
kind: Service
metadata:
  name: canary-analysis
spec:
  type: ClusterIP
  selector:
    app: canary-analysis
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
    name: http
